apiVersion: v1
kind: LimitRange
metadata:
  name: playground-limits
  namespace: playground
spec:
  limits:
    # Pod limits
    - type: Pod
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "10m"
        memory: "10Mi"

    # Container limits
    - type: Container
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "10m"
        memory: "10Mi"
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "10Gi"
      min:
        storage: "1Gi"
